services:
  web:
    image: hamdan27/reem-ai:latest
    build: .
    command: sh -c "uvicorn main:app --host=0.0.0.0 --port=8000"
    ports:
      - 8000:8000
    env_file:
      - ./app/.env
    volumes:
      - .:/reem-ai