export const realEstateQuestions = [
  "What is the current average sales price per square foot for apartments in Abu Dhabi?",
  "What is the current average sales price per square foot for villas in Abu Dhabi?",
  "What's the latest month-on-month change in apartment sales prices?",
  "What's the latest month-on-month change in villa sales prices?",
  "How much have apartment sales prices changed quarter-on-quarter?",
  "How much have villa sales prices changed quarter-on-quarter?",
  "What's the year-on-year change in apartment sales prices?",
  "What's the year-on-year change in villa sales prices?",
  "What was the sales price for apartments last month?",
  "What was the sales price for villas last month?",
  "What's the current price difference between apartment and villa sales?",
  "Which property type has higher sales prices currently?",
  "What was the highest recorded sales price for apartments in the dataset?",
  "What was the highest recorded sales price for villas in the dataset?",
  "What was the lowest recorded sales price for apartments in the dataset?",
  "What is the current average rental price per square foot for apartments?",
  "What is the current average rental price per square foot for villas?",
  "What's the latest month-on-month change in apartment rental prices?",
  "What's the latest month-on-month change in villa rental prices?",
  "How much have apartment rental prices changed quarter-on-quarter?",
  "How much have villa rental prices changed quarter-on-quarter?",
  "What's the year-on-year change in apartment rental prices?",
  "What's the year-on-year change in villa rental prices?",
  "What was the rental price for apartments last month?",
  "What was the rental price for villas last month?",
  "What's the current price difference between apartment and villa rentals?",
  "Which property type has higher rental prices currently?",
  "What was the highest recorded rental price for apartments in the dataset?",
  "What was the highest recorded rental price for villas in the dataset?",
  "What was the lowest recorded rental price for apartments in the dataset?",
  "Which property type showed stronger sales growth last month?",
  "Which property type showed stronger rental growth last month?",
  "How do current apartment sales and rental price changes compare?",
  "How do current villa sales and rental price changes compare?",
  "Which market segment shows higher year-on-year growth: sales or rentals?",
  "What's the price difference between apartments and villas in the sales market?",
  "What's the price difference between apartments and villas in the rental market?",
  "Which property type shows more price stability in sales?",
  "Which property type shows more price stability in rentals?",
  "How do quarterly changes compare between sales and rentals for apartments?",
  "What were the apartment sales prices three months ago?",
  "What were the villa sales prices three months ago?",
  "What were the apartment rental prices three months ago?",
  "What were the villa rental prices three months ago?",
  "How have apartment sales prices changed over the last quarter?",
  "How have villa sales prices changed over the last quarter?",
  "How have apartment rental prices changed over the last quarter?",
  "How have villa rental prices changed over the last quarter?",
  "Which month showed the strongest price growth in sales?",
  "Which month showed the strongest price growth in rentals?",
  "Which market segment shows higher year-on-year growth: sales or rentals?",
  "Give me some insights on the AD real estate market?"
];