name: Reem AI VM Deployment and CI/CD Pipeline

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'development'
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ ! -f requirements.txt ]; then echo "Error: requirements.txt not found"; exit 1; fi

  static-code-analysis:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit
      - name: Run bandit
        run: |
          bandit -r ./backend/

  deploy:
    needs: [build, static-code-analysis]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Deploy files to Azure VM
        uses: appleboy/scp-action@master
        with:
          host: 20.174.37.94
          username: viewitadmin
          password: ${{ secrets.AZURE_VM_PASSWORD }}
          port: 22
          source: "./backend"
          target: "/home/viewitadmin/reem-ai"
      
      - name: Execute commands on Azure VM
        uses: appleboy/ssh-action@master
        with:
          host: 20.174.37.94
          username: viewitadmin
          password: ${{ secrets.AZURE_VM_PASSWORD }}
          port: 22
          script: |
            echo "Commands to run on EC2"
            cd /home/viewitadmin/reem-ai
            echo "${{ secrets.ENV_FILE_CONTENT }}" > app/.env
            sudo docker compose down
            sudo docker compose up --build -d
            echo "Reem AI VM Deployment and CI/CD Pipeline Completed"
